version: '3.1'
services:
  postgresql:
    image: postgres:latest
    network_mode: bridge
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgresql
      POSTGRES_DB: database
      TZ: America/SaoPaulo
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    network_mode: bridge
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgresql
  