services:
  rabbitmq:
    image: rabbitmq:management
    network_mode: bridge
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      TZ: America/SaoPaulo
    ports:
      - 5672:5672
      - 15672:15672
