version: '3.1'
services:
  mysql:
    image: mysql:latest
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      TZ: America/SaoPaulo
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    network_mode: bridge
    ports:
      - 13306:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql
  