kafka:
  brokers:
    - "host.docker.internal:29092"
schemaRegistry:
  enabled: true
  urls:
    - "http://host.docker.internal:8081"

redpanda:
  adminApi:
    enabled: false

kafkaConnect:
  enabled: false
  clusters: []

server:
  listenPort: 8080

