services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://host.docker.internal:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr host.docker.internal:8082
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 29092:29092

  console:
    image: redpandadata/console:latest
    environment:
      - CONFIG_FILEPATH=/tmp/config.yml
    volumes:
      - ./config.yml:/tmp/config.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080"
    links:
      - redpanda
    depends_on:
      - redpanda
